### ISSUE TITLE
Investigate autogenerating group secrets

### ISSUE THREAD

**Issue by jiaweizhang** [jiaweizhang/duke-programming-contest#3]

**Comment by jiaweizhang** [comment]
@alexdao do we want to do what MSFT did with their coding challenge (randomly generated secrets used to join group) or do we want to specify custom secrets? If we do custom secrets, we have to check for duplicates and that allows people to accidentally stumble upon others secrets.

**Comment by alexdao** [comment]
I think we should just let them join "group names" of their own choosing. If it doesn't exist, it will create it. And then also have an option to leave a group, and if there are no members in the group, it will just delete the group.

**Comment by jiaweizhang** [comment]
I think we should just let them join "group names" of their own choosing. 
- No because that means I could join your group even if you didn't want me to (and wanted to form a group with your own friends)

If it doesn't exist, it will create it. And then also have an option to leave a group, and if there are no members in the group, it will just delete the group.
- This functionality exists already. When you select "join random group" (no secret specified), you either join a random group that was already created or you create a new random group

**Comment by jiaweizhang** [comment]
Unless we don't want to have a public display of "group names" in which case the "group names" would esseentially be "secrets"

**Comment by jiaweizhang** [comment]
Fixed using group names.
